name: Docker Build Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: skydrive:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker
      
      - name: Run Docker Compose validation
        run: |
          docker compose config